SS-1229 Fix of the bug not setting deleted on
ScilifelabDataCentre/serve pull request #264
Opened 2024-12-02 14:27 UTC by akochari

## Description

Describe your changes here to communicate to the maintainers why we should accept this pull request.
If it fixes a bug or resolves a feature request, be sure to include a link to that issue.

## Checklist

_If you're unsure about any of the items below, don't hesitate to ask. We're here to help!
This is simply a reminder of what we are going to look for before merging your code._

- [ ] This pull request is against **develop** branch (not applicable for hotfixes)
- [ ] I have included a link to the issue on GitHub or JIRA (if any)
- [ ] I have included migration files (if there are changes to the model classes)
- [ ] I have included, reviewed and executed tests (unit and end2end) to complement my changes
- [ ] I have updated the related documentation (if necessary)
- [ ] I have added a reviewer for this pull request
- [ ] I have added myself as an author for this pull request
- [ ] In the case I have modified settings.py, then I have also updated the studio-settings-configmap.yaml file in serve-charts

2024-12-04 14:26 UTC, alfredeen commented on studio/settings.py
> +TIME_ZONE = "Europe/Stockholm"
Line 295 also contains the TIME_ZONE setting and should be removed.

```suggestion
Please remove line 295 with the TIME_ZONE setting.
```

2024-12-04 14:28 UTC, alfredeen requested changes

2024-12-04 14:28 UTC, alfredeen commented on studio/settings.py
Line 295 also contains the TIME_ZONE setting and should be removed.

2024-12-04 14:35 UTC, akochari commented on studio/settings.py
I thought we could set the timezone. Is that not a good idea?

2024-12-04 15:24 UTC, alfredeen commented on studio/settings.py
Yes it is a good idea. The problem is that there is an existing line with TIME_ZONE = "UTC" that needs to be deleted so we do not have duplicate rows.

2024-12-05 08:39 UTC, alfredeen approved these changes
LGTM. Good work.

2024-12-05 08:42 UTC, merged